swagger: '2.0'
info:
  title: DaVinci API
  description: API for Da Vinci Art
  version: '1.0.0'
host: 'localhost:3001'
basePath: '/'
schemes:
  - http
paths:
  /collection/getTopFive:
    get:
      summary: Get top five collections
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Collection'

  /collection/getPopular:
    get:
      summary: Get popular collections
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Collection'

  /payment/{collectionId}/buy:
    post:
      summary: Buy a collection
      parameters:
        - name: collectionId
          in: path
          required: true
          type: string
      responses:
        200:
          description: Purchase successful

  /user/{userId}/collection/{collectionId}/get:
    get:
      summary: Get collection with painting
      parameters:
        - name: collectionId
          in: path
          required: true
          type: string
        - name: userId
          in: path
          required: true
          type: string
      responses:
        200:
          description: Successful response

  /user/{userId}/collection/getAll:
    get:
      summary: Get all collections by user ID
      parameters:
                 - name: userId
                   in: path
                   required: true
                   type: string
      responses:
        200:
          description: Successful response

  /auth/register:
    post:
      summary: Register a new user
      responses:
        200:
          description: Registration successful

  /auth/login:
    post:
      summary: Login a user
      responses:
        200:
          description: Login successful

  /auth/refresh:
    post:
      summary: Refresh authentication
      responses:
        200:
          description: Refresh successful

  /auth/verifyEmail:
    post:
      summary: Verify user email
      responses:
        200:
          description: Verification successful

  /reviews/sendReview/{userId}:
    post:
      summary: Add a review
      parameters:
        - name: userId
          in: path
          required: true
          type: string
      responses:
        200:
          description: Review added successfully

  /reviews/{userId}/getAll:
    get:
      summary: Get all reviews by user ID
      parameters:
        - name: userId
          in: path
          required: true
          type: string
      responses:
        200:
          description: Successful response

  /user/get:
    get:
      summary: Get user by query
      responses:
        200:
          description: Successful response

  /user/{userId}/delete:
    delete:
      summary: Delete a user
      parameters:
        - name: userId
          in: path
          required: true
          type: string
      responses:
        200:
          description: User deleted successfully

  /user/{userId}/update:
    put:
      summary: Update a user
      parameters:
        - name: userId
          in: path
          required: true
          type: string
      responses:
        200:
          description: User updated successfully

  /user/{userId}/collection/add:
            post:
              summary: Add a new collection
              parameters:
                - name: userId
                  in: path
                  required: true
                  type: string
              responses:
                200:
                  description: Collection added successfully

  /user/{userId}/collection/{collectionId}/edit:
              put:
                summary: Edit a collection
                parameters:
                  - name: collectionId
                    in: path
                    required: true
                    type: string
                  - name: userId
                    in: path
                    required: true
                    type: string
                responses:
                  200:
                    description: Collection edited successfully

  /reviews/{reviewId}/delete:
              delete:
                summary: Delete a review
                parameters:
                  - name: reviewId
                    in: path
                    required: true
                    type: string
                responses:
                  200:
                    description: Review deleted successfully

  /reviews/{reviewId}/edit:
              put:
                summary: Edit a review
                parameters:
                  - name: reviewId
                    in: path
                    required: true
                    type: string
                responses:
                  200:
                    description: Review edited successfully


  /user/{userId}/getAllComments:
              get:
                summary: Get all comments for a user
                parameters:
                  - name: userId
                    in: path
                    required: true
                    type: string
                responses:
                  200:
                    description: Successful response

definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      email:
        type: string
      password:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time

  Collection:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      description:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time

  Review:
    type: object
    properties:
      id:
        type: integer
        format: int64
      userId:
        type: integer
        format: int64
      content:
        type: string
      rating:
        type: integer
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time

  Payment:
    type: object
    properties:
      id:
        type: integer
        format: int64
      userId:
        type: integer
        format: int64
      collectionId:
        type: integer
        format: int64
      amount:
        type: number
        format: float
      status:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time

  Comment:
    type: object
    properties:
      id:
        type: integer
        format: int64
      userId:
        type: integer
        format: int64
      content:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time

  Painting:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        artist:
          type: string
        year:
          type: integer
        description:
          type: string
        imageUrl:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

  Transaction:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        amount:
          type: number
          format: float
        transactionType:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time